THIS IS MY PANDAS ASSIGNMENT!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
path = '../../data/honey.csv'
df = pd.read_csv(path)
print(df)

    state    numcol  yieldpercol   totalprod      stocks  priceperlb  \
0      AL   16000.0           71   1136000.0    159000.0        0.72
1      AZ   55000.0           60   3300000.0   1485000.0        0.64
2      AR   53000.0           65   3445000.0   1688000.0        0.59
3      CA  450000.0           83  37350000.0  12326000.0        0.62
4      CO   27000.0           72   1944000.0   1594000.0        0.70
..    ...       ...          ...         ...         ...         ...
621    VA    4000.0           41    164000.0     23000.0        3.77
622    WA   62000.0           41   2542000.0   1017000.0        2.38
623    WV    6000.0           48    288000.0     95000.0        2.91
624    WI   60000.0           69   4140000.0   1863000.0        2.05
625    WY   50000.0           51   2550000.0    459000.0        1.87

      prodvalue  year
0      818000.0  1998
1     2112000.0  1998
2     2033000.0  1998
3    23157000.0  1998
4     1361000.0  1998
..          ...   ...
621    618000.0  2012
622   6050000.0  2012
623    838000.0  2012
624   8487000.0  2012
625   4769000.0  2012

[626 rows x 8 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        626 non-null    object
 1   numcol       626 non-null    float64
 2   yieldpercol  626 non-null    int64
 3   totalprod    626 non-null    float64
 4   stocks       626 non-null    float64
 5   priceperlb   626 non-null    float64
 6   prodvalue    626 non-null    float64
 7   year         626 non-null    int64
dtypes: float64(5), int64(2), object(1)
memory usage: 39.3+ KB

In [5]:
df.head()

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998
1,AZ,55000.0,60,3300000.0,1485000.0,0.64,2112000.0,1998
2,AR,53000.0,65,3445000.0,1688000.0,0.59,2033000.0,1998
3,CA,450000.0,83,37350000.0,12326000.0,0.62,23157000.0,1998
4,CO,27000.0,72,1944000.0,1594000.0,0.70,1361000.0,1998

In [6]:
df.tail()

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year
621,VA,4000.0,41,164000.0,23000.0,3.77,618000.0,2012
622,WA,62000.0,41,2542000.0,1017000.0,2.38,6050000.0,2012
623,WV,6000.0,48,288000.0,95000.0,2.91,838000.0,2012
624,WI,60000.0,69,4140000.0,1863000.0,2.05,8487000.0,2012
625,WY,50000.0,51,2550000.0,459000.0,1.87,4769000.0,2012

In [7]:
path2 = '../../data/birds.csv'
df.birds = pd.read_csv(path2)
print(df.birds)

                             Name          ScientificName  \
0    Black-bellied whistling-duck  Dendrocygna autumnalis
1          Fulvous whistling-duck     Dendrocygna bicolor
2                      Snow goose      Anser caerulescens
3                    Ross's goose            Anser rossii
4     Greater white-fronted goose         Anser albifrons
..                            ...                     ...
438                 Blue grosbeak      Passerina caerulea
439                Lazuli bunting        Passerina amoena
440                Indigo bunting        Passerina cyanea
441               Painted bunting         Passerina ciris
442                    Dickcissel         Spiza americana

                  Category          Order        Family        Genus  \
0    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
1    Ducks/Geese/Waterfowl   Anseriformes      Anatidae  Dendrocygna
2    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
3    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
4    Ducks/Geese/Waterfowl   Anseriformes      Anatidae        Anser
..                     ...            ...           ...          ...
438       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
439       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
440       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
441       Cardinals/Allies  Passeriformes  Cardinalidae    Passerina
442       Cardinals/Allies  Passeriformes  Cardinalidae        Spiza

    ConservationStatus  MinLength  MaxLength  MinBodyMass  MaxBodyMass  \
0                   LC       47.0       56.0        652.0       1020.0
1                   LC       45.0       53.0        712.0       1050.0
2                   LC       64.0       79.0       2050.0       4050.0
3                   LC       57.3       64.0       1066.0       1567.0
4                   LC       64.0       81.0       1930.0       3310.0
..                 ...        ...        ...          ...          ...
438                 LC       14.0       19.0         26.0         31.5
439                 LC       13.0       15.0         13.0         18.0
440                 LC       11.5       15.0         11.2         21.4
441                 LC       12.0       14.0         13.0         19.0
442                 LC       14.0       16.0         25.6         38.4

     MinWingspan  MaxWingspan
0           76.0         94.0
1           85.0         93.0
2          135.0        165.0
3          113.0        116.0
4          130.0        165.0
..           ...          ...
438         26.0         29.0
439         22.0         22.0
440         18.0         23.0
441         21.0         23.0
442         24.8         26.0

[443 rows x 13 columns]

C:\Users\Vickysong\AppData\Local\Temp\ipykernel_13720\1273790544.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.birds = pd.read_csv(path2)

In [8]:
df.birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                443 non-null    object
 1   ScientificName      443 non-null    object
 2   Category            443 non-null    object
 3   Order               443 non-null    object
 4   Family              443 non-null    object
 5   Genus               443 non-null    object
 6   ConservationStatus  443 non-null    object
 7   MinLength           443 non-null    float64
 8   MaxLength           443 non-null    float64
 9   MinBodyMass         443 non-null    float64
 10  MaxBodyMass         443 non-null    float64
 11  MinWingspan         443 non-null    float64
 12  MaxWingspan         443 non-null    float64
dtypes: float64(6), object(7)
memory usage: 45.1+ KB

In [9]:
df.birds.head()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
0,Black-bellied whistling-duck,Dendrocygna autumnalis,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,47.0,56.0,652.0,1020.0,76.0,94.0
1,Fulvous whistling-duck,Dendrocygna bicolor,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Dendrocygna,LC,45.0,53.0,712.0,1050.0,85.0,93.0
2,Snow goose,Anser caerulescens,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,79.0,2050.0,4050.0,135.0,165.0
3,Ross's goose,Anser rossii,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,57.3,64.0,1066.0,1567.0,113.0,116.0
4,Greater white-fronted goose,Anser albifrons,Ducks/Geese/Waterfowl,Anseriformes,Anatidae,Anser,LC,64.0,81.0,1930.0,3310.0,130.0,165.0

In [10]:
df.birds.tail()

,Name,ScientificName,Category,Order,Family,Genus,ConservationStatus,MinLength,MaxLength,MinBodyMass,MaxBodyMass,MinWingspan,MaxWingspan
438,Blue grosbeak,Passerina caerulea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,14.0,19.0,26.0,31.5,26.0,29.0
439,Lazuli bunting,Passerina amoena,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,13.0,15.0,13.0,18.0,22.0,22.0
440,Indigo bunting,Passerina cyanea,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,11.5,15.0,11.2,21.4,18.0,23.0
441,Painted bunting,Passerina ciris,Cardinals/Allies,Passeriformes,Cardinalidae,Passerina,LC,12.0,14.0,13.0,19.0,21.0,23.0
442,Dickcissel,Spiza americana,Cardinals/Allies,Passeriformes,Cardinalidae,Spiza,LC,14.0,16.0,25.6,38.4,24.8,26.0

In [11]:
path3 ='../../data/mushrooms.csv'
df.path3 = pd.read_csv(path3)
print(df.path3)

          class cap-shape cap-surface cap-color     bruises     odor  \
0     Poisonous    Convex      Smooth     Brown     Bruises  Pungent
1        Edible    Convex      Smooth    Yellow     Bruises   Almond
2        Edible      Bell      Smooth     White     Bruises    Anise
3     Poisonous    Convex       Scaly     White     Bruises  Pungent
4        Edible    Convex      Smooth     Green  No Bruises      NaN
...         ...       ...         ...       ...         ...      ...
8119     Edible   Knobbed      Smooth     Brown  No Bruises      NaN
8120     Edible    Convex      Smooth     Brown  No Bruises      NaN
8121     Edible      Flat      Smooth     Brown  No Bruises      NaN
8122  Poisonous   Knobbed       Scaly     Brown  No Bruises    Fishy
8123     Edible    Convex      Smooth     Brown  No Bruises      NaN

     gill-attachment gill-spacing gill-size gill-color  ...  \
0               Free        Close    Narrow      Black  ...
1               Free        Close     Broad      Black  ...
2               Free        Close     Broad      Brown  ...
3               Free        Close    Narrow      Brown  ...
4               Free      Crowded     Broad      Black  ...
...              ...          ...       ...        ...  ...
8119        Attached        Close     Broad     Yellow  ...
8120        Attached        Close     Broad     Yellow  ...
8121        Attached        Close     Broad      Brown  ...
8122            Free        Close    Narrow       Buff  ...
8123        Attached        Close     Broad     Yellow  ...

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                      Smooth                  White                  White
1                      Smooth                  White                  White
2                      Smooth                  White                  White
3                      Smooth                  White                  White
4                      Smooth                  White                  White
...                       ...                    ...                    ...
8119                   Smooth                 Orange                 Orange
8120                   Smooth                 Orange                 Orange
8121                   Smooth                 Orange                 Orange
8122                    Silky                  White                  White
8123                   Smooth                 Orange                 Orange

     veil-type veil-color ring-number   ring-type spore-print-color  \
0      Partial      White         One     Pendant             Black
1      Partial      White         One     Pendant             Brown
2      Partial      White         One     Pendant             Brown
3      Partial      White         One     Pendant             Black
4      Partial      White         One  Evanescent             Brown
...        ...        ...         ...         ...               ...
8119   Partial     Orange         One     Pendant              Buff
8120   Partial      Brown         One     Pendant              Buff
8121   Partial     Orange         One     Pendant              Buff
8122   Partial      White         One  Evanescent             White
8123   Partial     Orange         One     Pendant            Orange

     population  habitat
0     Scattered    Urban
1      Numerous  Grasses
2      Numerous  Meadows
3     Scattered    Urban
4      Abundant  Grasses
...         ...      ...
8119  Clustered   Leaves
8120    Several   Leaves
8121  Clustered   Leaves
8122    Several   Leaves
8123  Clustered   Leaves

[8124 rows x 23 columns]

C:\Users\Vickysong\AppData\Local\Temp\ipykernel_13720\3511027483.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.path3 = pd.read_csv(path3)

In [12]:
df.path3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      4596 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8088 non-null   object
 19  ring-type                 8088 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB